### ISSUE TITLE
Unknown DNSSEC Lookup Failure on Android

### ISSUE THREAD

**Issue by schildbach** [netkicorp/java-wns-resolver#5]
On Android, with the latest version from master plus my recent PRs appied, I run into this generic exception:

```
com.netki.exceptions.WalletNameLookupException: Unknown DNSSEC Lookup Failure
	at com.netki.WalletNameResolver.resolve(WalletNameResolver.java:159)
	at com.netki.WalletNameResolver.resolve(WalletNameResolver.java:162)
	at com.netki.WalletNameResolver.resolve(WalletNameResolver.java:162)
	at de.schildbach.wallet.ui.send.SendCoinsFragment$13.run(SendCoinsFragment.java:846)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:135)
	at android.os.HandlerThread.run(HandlerThread.java:61)
Caused by: com.netki.exceptions.DNSSECException: Unknown DNSSEC Lookup Failure
	at com.netki.dnssec.DNSSECResolver.resolve(DNSSECResolver.java:148)
	at com.netki.WalletNameResolver.resolve(WalletNameResolver.java:153)
	... 7 more
```

It's currently not clear to me why this is happening. Maybe the exception needs to be improved?

**Comment by techguy613** [comment]
Hey @schildbach, can you tell me what you were looking up when this happened so I can try to reproduce? This error only occurs when a response is returned, but contains no positive or negative resolution. I can update the exception to be more specific, but I'd also like to see what condition is causing this.

**Comment by schildbach** [comment]
I think I was querying for a name that just wasn't in the DNS. Name "andreas.schildbach.de", currency "tbtc" – but I've now added the DNS entry and it proceeds further to another exception … investigating …

**Comment by schildbach** [comment]
Thanks for the message change. However I think we need a more concise API at that point. I suggest either `resolve()` to return `null`, or we introduce a specific exception type (subclass of WalletNameResolverException). Since the input data will origin from users in most cases, I tend to prefer the first option.

**Comment by techguy613** [comment]
I've updated the API to return null when a valid negative response is received, which was the case here.
